### ISSUE TITLE
unexpected actions

### ISSUE THREAD

**Issue by mustafaekim** [KillerCodeMonkey/ng2-quill#2]
hi, the does the demo work for you? I checked your live demo and the editor behaves very buggy. the cursor randomly goes to the beginning of the text, some spaces are removed and there happen a huge number of **selectionaction** event on the background.

**Comment by mmoravcik** [comment]
I had the same problems with version 1.1.5.
Now I am using 1.1.6 and everything works fine for me

**Comment by KillerCodeMonkey** [comment]
the demo is working for me. No strange behaves at all in current chrome.

**Comment by mustafaekim** [comment]
oh, very bizarre. I've updated chrome but the problems still exist for me. I tried many different versions of quill including beta, 1.0, 1.1.5 and 1.1.6. (on firefox it works fine)

**Comment by mustafaekim** [comment]
by the way, the exact same problem occur in primeng's editor (which is also based on ang2 + quill)

**Comment by KillerCodeMonkey** [comment]
i have updated everything.. quilljs, angular-cli, ... fixed the order of the contentChanged event and fixed setting the touched state. --> release 0.0.6

The last editor in the demo shows now the model-change.

and everything is working for me... in chrome (Version 54.0.2840.98 (64-bit)), firefox (50.0.2) and safari (Version 10.0.1 (12602.2.14.0.7)) on mac osx sierra.

Even on my Xiaomi Mi4c Android Smartphone everything works fine :(

**Comment by mustafaekim** [comment]
thank you very much for being supportive. I think that I figured out the problem: "Grammarly for Chrome" extension. I think that grammarly is  raising some events on every selection change and hence that somehow results with an infinite event loop when intermixed with angular or quill)

**Comment by KillerCodeMonkey** [comment]
Strange. I've got some angular2 errors while testing some angular2 chrome extensions, but this is strange :D 

So feel free to close the issue, if now everything works
